#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-ggplot2
Version  : 1.0.1
Release  : 14
URL      : http://cran.r-project.org/src/contrib/ggplot2_1.0.1.tar.gz
Source0  : http://cran.r-project.org/src/contrib/ggplot2_1.0.1.tar.gz
Summary  : An Implementation of the Grammar of Graphics
Group    : Development/Tools
License  : GPL-2.0
Requires: R-proto
Requires: R-plyr
Requires: R-scales
Requires: R-reshape2
Requires: R-gtable
BuildRequires : R-gtable
BuildRequires : R-plyr
BuildRequires : R-proto
BuildRequires : R-reshape2
BuildRequires : R-scales
BuildRequires : clr-R-helpers

%description
# ggplot2
[![Build Status](https://travis-ci.org/hadley/ggplot2.png?branch=master)](https://travis-ci.org/hadley/ggplot2)

%prep
%setup -q -c -n ggplot2

%build

%install
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -ffunction-sections -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --build  -l %{buildroot}/usr/lib64/R/library ggplot2
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library ggplot2 || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ggplot2/CITATION
/usr/lib64/R/library/ggplot2/DESCRIPTION
/usr/lib64/R/library/ggplot2/INDEX
/usr/lib64/R/library/ggplot2/Meta/Rd.rds
/usr/lib64/R/library/ggplot2/Meta/data.rds
/usr/lib64/R/library/ggplot2/Meta/hsearch.rds
/usr/lib64/R/library/ggplot2/Meta/links.rds
/usr/lib64/R/library/ggplot2/Meta/nsInfo.rds
/usr/lib64/R/library/ggplot2/Meta/package.rds
/usr/lib64/R/library/ggplot2/Meta/vignette.rds
/usr/lib64/R/library/ggplot2/NAMESPACE
/usr/lib64/R/library/ggplot2/NEWS
/usr/lib64/R/library/ggplot2/R/ggplot2
/usr/lib64/R/library/ggplot2/R/ggplot2.rdb
/usr/lib64/R/library/ggplot2/R/ggplot2.rdx
/usr/lib64/R/library/ggplot2/data/Rdata.rdb
/usr/lib64/R/library/ggplot2/data/Rdata.rds
/usr/lib64/R/library/ggplot2/data/Rdata.rdx
/usr/lib64/R/library/ggplot2/data/datalist
/usr/lib64/R/library/ggplot2/doc/development.R
/usr/lib64/R/library/ggplot2/doc/development.Rmd
/usr/lib64/R/library/ggplot2/doc/development.html
/usr/lib64/R/library/ggplot2/doc/index.html
/usr/lib64/R/library/ggplot2/doc/release.R
/usr/lib64/R/library/ggplot2/doc/release.Rmd
/usr/lib64/R/library/ggplot2/doc/release.html
/usr/lib64/R/library/ggplot2/help/AnIndex
/usr/lib64/R/library/ggplot2/help/aliases.rds
/usr/lib64/R/library/ggplot2/help/ggplot2.rdb
/usr/lib64/R/library/ggplot2/help/ggplot2.rdx
/usr/lib64/R/library/ggplot2/help/paths.rds
/usr/lib64/R/library/ggplot2/html/00Index.html
/usr/lib64/R/library/ggplot2/html/R.css
/usr/lib64/R/library/ggplot2/staticdocs/README.md
/usr/lib64/R/library/ggplot2/staticdocs/footer.html
/usr/lib64/R/library/ggplot2/staticdocs/head.html
/usr/lib64/R/library/ggplot2/staticdocs/icons.R
/usr/lib64/R/library/ggplot2/staticdocs/index.r
/usr/lib64/R/library/ggplot2/test_ns/DESCRIPTION
/usr/lib64/R/library/ggplot2/test_ns/NAMESPACE
/usr/lib64/R/library/ggplot2/test_ns/R/my-plot.r
/usr/lib64/R/library/ggplot2/test_ns/man/my_plot.Rd
/usr/lib64/R/library/ggplot2/tests/helper-plot-data.r
/usr/lib64/R/library/ggplot2/tests/test-aes-grouping.r
/usr/lib64/R/library/ggplot2/tests/test-aes-setting.r
/usr/lib64/R/library/ggplot2/tests/test-aes.r
/usr/lib64/R/library/ggplot2/tests/test-all.R
/usr/lib64/R/library/ggplot2/tests/test-boxplot.r
/usr/lib64/R/library/ggplot2/tests/test-build.r
/usr/lib64/R/library/ggplot2/tests/test-coord-polar.r
/usr/lib64/R/library/ggplot2/tests/test-coord-train.r
/usr/lib64/R/library/ggplot2/tests/test-data.r
/usr/lib64/R/library/ggplot2/tests/test-dotplot.r
/usr/lib64/R/library/ggplot2/tests/test-empty-data.r
/usr/lib64/R/library/ggplot2/tests/test-facet-.r
/usr/lib64/R/library/ggplot2/tests/test-facet-layout.r
/usr/lib64/R/library/ggplot2/tests/test-facet-locate.r
/usr/lib64/R/library/ggplot2/tests/test-fortify.r
/usr/lib64/R/library/ggplot2/tests/test-labels.r
/usr/lib64/R/library/ggplot2/tests/test-layer.r
/usr/lib64/R/library/ggplot2/tests/test-qplot.r
/usr/lib64/R/library/ggplot2/tests/test-scale-manual.r
/usr/lib64/R/library/ggplot2/tests/test-scales-breaks-labels.r
/usr/lib64/R/library/ggplot2/tests/test-scales.r
/usr/lib64/R/library/ggplot2/tests/test-stats.r
/usr/lib64/R/library/ggplot2/tests/test-theme.r
/usr/lib64/R/library/ggplot2/tests/test-utilities.r
